version: "3.7"

services:
    web:
      build: .
      expose:
        - 3000
    node:
      image: "alpine3.15"
  
    jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      ports:
        - "8080:8080"
      
