version: "3.7"

services:
    web:
      build: .
      ports:
        - "3000:3000"
    node:
      image: "alpine:latest"
  
    jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      ports:
        - "8080:8080"
      
